networks:
    traefik_network:
        external: true
services:
    nexus:
        container_name: nexus
        environment:
            - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g
        expose:
            - "8081"
        image: sonatype/nexus3:3.96.0-alpine
        labels:
            - traefik.enable=true
            - traefik.http.routers.registry-svc.rule=Host(`registry.nas.svc.h.mirceanton.com`)
            - traefik.http.routers.registry-svc.entrypoints=websecure
            - traefik.http.routers.registry-svc.tls.certresolver=cloudflare
            - traefik.http.routers.registry-svc.service=registry
            - traefik.http.services.registry.loadbalancer.server.port=8081
        networks:
            - traefik_network
        restart: unless-stopped
        user: 568:568
        volumes:
            - /mnt/scratch/Nexus_Data:/nexus-data
