---
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.6.4
    restart: unless-stopped
    command: start
    expose: ["8080"]
    networks: ["traefik_network"]
    environment:
      - TZ=Europe/Bucharest
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_HOSTNAME=keycloak.nas.svc.h.mirceanton.com
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          exec 3<>/dev/tcp/localhost/9000 &&
          echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 &&
          cat <&3 | grep -q '200 OK'
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.nas.svc.h.mirceanton.com`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=cloudflare"
    depends_on:
      keycloak-db:
        condition: service_healthy

  keycloak-db:
    container_name: keycloak-db
    image: docker.io/postgres:18.4-alpine
    restart: unless-stopped
    networks: ["traefik_network"]
    volumes: [keycloak-db-data:/var/lib/postgresql]
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  lldap:
    container_name: lldap
    image: ghcr.io/lldap/lldap:2026-05-26-alpine
    restart: unless-stopped
    volumes: [lldap-data:/data]
    expose: ["17170", "3890"]
    ports:
      - "10.0.10.245:3890:3890"
    networks: ["traefik_network"]
    environment:
      - TZ=Europe/Bucharest
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_LDAP_BASE_DN=dc=mirceanton,dc=com
      - LLDAP_LDAP_USER_PASS=${LLDAP_ADMIN_PASSWORD}
      - LLDAP_HTTP_URL=https://lldap.nas.svc.h.mirceanton.com
    healthcheck:
      test: ["CMD", "/app/lldap", "healthcheck", "--config-file", "/data/lldap_config.toml"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lldap.rule=Host(`lldap.nas.svc.h.mirceanton.com`)"
      - "traefik.http.routers.lldap.entrypoints=websecure"
      - "traefik.http.routers.lldap.tls.certresolver=cloudflare"
      - "traefik.http.routers.lldap.service=lldap"
      - "traefik.http.services.lldap.loadbalancer.server.port=17170"

networks:
  traefik_network:
    external: true

volumes:
  keycloak-db-data:
    driver: local
  lldap-data:
    driver: local
