resource "sonatyperepo_repository_pypi_proxy" "pypi_proxy" {
  name   = "pypi-proxy"
  online = true

  storage = {
    blob_store_name                = "default"
    strict_content_type_validation = true
  }

  proxy = {
    remote_url       = "https://pypi.org"
    content_max_age  = 1440
    metadata_max_age = 1440
  }

  negative_cache = {
    enabled      = true
    time_to_live = 1440
  }

  http_client = {
    auto_block = false
    blocked    = false

    connection = {
      enable_circular_redirects = true
      enable_cookies            = true
      retries                   = 3
      timeout                   = 60
      use_trust_store           = false
    }
  }
}

import {
  to = sonatyperepo_repository_pypi_proxy.pypi_proxy
  id = "pypi-proxy"
}

resource "sonatyperepo_repository_pypi_hosted" "pypi_hosted" {
  name   = "pypi-local"
  online = true

  storage = {
    blob_store_name                = "default"
    strict_content_type_validation = true
    write_policy                   = "ALLOW"
  }
}

import {
  to = sonatyperepo_repository_pypi_hosted.pypi_hosted
  id = "pypi-local"
}

resource "sonatyperepo_repository_pypi_group" "pypi_group" {
  name   = "pypi-all"
  online = true

  storage = {
    blob_store_name                = "default"
    strict_content_type_validation = true
  }

  group = {
    member_names = [
      sonatyperepo_repository_pypi_hosted.pypi_hosted.name,
      sonatyperepo_repository_pypi_proxy.pypi_proxy.name,
    ]
  }
}

import {
  to = sonatyperepo_repository_pypi_group.pypi_group
  id = "pypi-all"
}
